name: PlatformIO Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build PlatformIO Project
        run: pio run -d Servo-Driver-with-ESP32

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: Servo-Driver-with-ESP32/.pio/build/esp32dev/firmware.bin
